version: "0.5"

processes:
  kmm:
    command: kmm serve
    depends_on:
      nats-server:
        condition: process_log_ready

  nats-server:
    command: nats server run kmm --jetstream
    ready_log_line: "Server is ready"   
